import { Matches } from './match';

export const MATCHES: Matches[] = [
    {mno:1,btw:'Team A v/s Team B',toss:'Team has A decided to Bowl First',venue:'Wankhede Cricket Stadium',date:'22-02-2020',result:'Team B wins',scores:{os:'326/8',sc:'325',highrunone:{name:'Sachin',runs:125},highruntwo:{name:'Saurav',runs:149},highwicone:{name:'Akram',wick:6},highwictwo:{name:'Warne',wick:3}}},
    {mno:2,btw:'Team C v/s Team D',toss:'Team has D decided to Bowl First',venue:'Eden Garden Cricket Stadium',date:'22-02-2020',result:'Team C wins',scores:{os:'245',sc:'250',highrunone:{name:'Lara',runs:87},highruntwo:{name:'Rohit',runs:112},highwicone:{name:'Aamir',wick:4},highwictwo:{name:'Mcgarth',wick:3}}},
    {mno:3,btw:'Team B v/s Team D',toss:'Team has B decided to Bat First',venue:'Oval Cricket Stadium',date:'25-02-2020',result:'Team B wins',scores:{os:'298/4',sc:'246',highrunone:{name:'Kumar',runs:106},highruntwo:{name:'Shewag',runs:74},highwicone:{name:'Bumrah',wick:5},highwictwo:{name:'Waqar',wick:4}}},
    {mno:4,btw:'Team A v/s Team C',toss:'Team has C decided to Bowl First',venue:'Lords Cricket Stadium',date:'25-02-2020',result:'Team A wins',scores:{os:'189',sc:'190/2',highrunone:{name:'Ricky',runs:61},highruntwo:{name:'Lloyd',runs:89},highwicone:{name:'Kapil',wick:6},highwictwo:{name:'Steyn',wick:2}}},
    {mno:5,btw:'Team A v/s Team D',toss:'Team has D decided to Bat First',venue:'Melbounre Cricket Stadium',date:'27-02-2020',result:'Team D wins',scores:{os:'245/5',sc:'241',highrunone:{name:'Rohit',runs:87},highruntwo:{name:'Virat',runs:99},highwicone:{name:'Warne',wick:3},highwictwo:{name:'Aamir',wick:4}}},
    {mno:6,btw:'Team B v/s Team C',toss:'Team has B decided to Bowl First',venue:'Sydney Cricket Stadium',date:'27-02-2020',result:'Team C wins',scores:{os:'360',sc:'362/9',highrunone:{name:'Dravid',runs:149},highruntwo:{name:'Lara',runs:182},highwicone:{name:'Steyn',wick:4},highwictwo:{name:'Zaheer',wick:2}}},
    {mno:7,btw:'Team C v/s Team A',toss:'Team has C decided to Bat First',venue:'Kingsmead Cricket Stadium',date:'29-02-2020',result:'Team A wins',scores:{os:'159',sc:'121',highrunone:{name:'Kallis',runs:45},highruntwo:{name:'Kapil',runs:49},highwicone:{name:'Warne',wick:2},highwictwo:{name:'Sobers',wick:5}}},
    {mno:8,btw:'Team A v/s Team D',toss:'Team has A decided to Bat First',venue:'Trent Bridge Cricket Stadium',date:'29-02-2020',result:'Team D wins',scores:{os:'248/4',sc:'211',highrunone:{name:'Richards',runs:100},highruntwo:{name:'Rahane',runs:79},highwicone:{name:'Bumrah',wick:5},highwictwo:{name:'Murali',wick:4}}},
    {mno:9,btw:'Team A v/s Team B',toss:'Team has A decided to Bat First',venue:'Wankhede Cricket Stadium',date:'02-03-2020',result:'Team B wins',scores:{os:'326/8',sc:'325',highrunone:{name:'MSD',runs:125},highruntwo:{name:'Sachin',runs:148},highwicone:{name:'Akram',wick:6},highwictwo:{name:'Murali',wick:3}}},
    {mno:10,btw:'Team D v/s Team B',toss:'Team has B decided to Bowl First',venue:'Trent Bridge Cricket Stadium',date:'04-03-2020',result:'Team B wins',scores:{os:'325/7',sc:'329/5',highrunone:{name:'Saurav',runs:165},highruntwo:{name:'Laxman',runs:126},highwicone:{name:'Cummins',wick:2},highwictwo:{name:'Waqar',wick:3}}},
]
